### ISSUE TITLE
missing DOI for some pubmed ids 

### ISSUE THREAD

**Issue by jhpoelen** [PHI-base/data#1]
Hi! Thanks for sharing this valuable resources in an easy to parse csv format.

I noticed that 82 pubmed ids have associated dois, but have not yet been populated in [phi-base_v4-5_2018-05-15.csv](../blob/master/releases/phi-base_v4-5_2018-05-15.csv) . 

See attached list for suggested pubmed id - doi pairs. 
[pmidWithDOI.tsv.txt](https://github.com/PHI-base/data/files/2116581/pmidWithDOI.tsv.txt)

**Comment by CuzickA** [comment]
Hi @jhpoelen I'm glad you like our csv files.

Thank you for your helpful list of suggested pubmed id - doi pairs. I will take a look and make the changes for our phi-base version 4.6 release due in November 2018.

**Comment by CuzickA** [comment]
DOIs have now been added to Excel spreadsheet in preparation for 4.6 release.
