### ISSUE TITLE
Add lists of PHI-Canto pathogen and host species

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/data#10]
Required for moving forward with PHI-Canto roll out and manuscript preparation.

**Comment by jseager7** [comment]
@CuzickA The PHI-Canto host species list currently has no column headings, and the columns are in a different order to the strain list. Would you be okay with these proposed column names and column order in the example below? The same could be used for the pathogen list.

ncbi_taxid | scientific_name | common_name
-- | -- | --
2708 | Citrus limon | lemon
