### ISSUE TITLE
Fix warnings in the PHI-base GAF file

### ISSUE THREAD

**Issue by jseager7** [PHI-base/data#15]
@ValWood Here's the issue to discuss fixing errors in the PHI-base GAF file.

The latest GAF file is here: https://github.com/PHI-base/data/blob/master/phibase.gaf

Pascale noted that there's an [error report](http://release.geneontology.org/2023-05-10/reports/assigned-by-PHI-base-report.html ) on GO Central dated 10 May, which I've looked at.

However, this report only contains a total of four errors related to [GORULE:0000027](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000027.md), specifically that the values of the 'assigned by' column for these rows are "not present in groups reference", which presumably means that the 'assigned by' value does not match a group in [groups.yaml](https://github.com/geneontology/go-site/blob/master/metadata/groups.yaml) on the go-site repository.

(Just to note, the pull request that was closed on go-site (https://github.com/geneontology/go-site/pull/1543) was meant to add an entry to groups.yaml for PHI-base, which would presumably fix these errors.)

I'm confused as to why there are only four errors, since if PHI-base is missing from the groups file, then presumably every line in the GAF file should be raising this error. Maybe the report stops after a set number of errors, either for each rule or globally.

I'm still not sure how to get an up to date error report in the line by line format that Alex provided in the original pull request. I was hoping there would be some way to run the checks on a local machine, but I can't find where the code is located.

I'm also not sure if the GO report is using the [latest version](https://raw.githubusercontent.com/PHI-base/data/master/phibase.gaf) of the GAF file from this repository. As I understand it, GO Central uses the locations specified in the [datasets folder](https://github.com/geneontology/go-site/tree/master/metadata/datasets) on the go-site repository to find the GAF file (see the [pombase dataset file](https://github.com/geneontology/go-site/blob/master/metadata/datasets/pombase.yaml) as an example), but there currently isn't a dataset file for PHI-base. Again, this is something the pull request was trying to fix.

In the original pull request, you noted that PHI-base is probably not a database authority for most (or all) of the species in PHI-base, and that in these cases, "the 'ownership' devolves to GOA". So it's not clear to me whether PHI-base really deserves an entry in the datasets folder – but if it doesn't, then it's not clear to me how we specify where GO Central should look for the PHI-base GAF file.

**Comment by ValWood** [comment]
Thre are 2 checking systems
1. the One GO ones
2. the one GO ones. 
They are largely overlapping but I think there are more checks i the GOA file.

I notice that some of the extensions you are exporting are either
i) out of date
ii) not GO extensions
for example "has_direct_input" is replaced by "direct_input"
and the host species extensions "with_host_species(4530)" is not a GO extension. For GO the host species should be included in the taxon ID field (pipe separated with the pathogen)

One you have a full list of the problems I can help with the non-obvious ones.

**Comment by jseager7** [comment]
> Thre are 2 checking systems
    the One GO ones
    the one GO ones.

Do you mean there's one checking system for GO and another for GOA?

**Comment by ValWood** [comment]
Yes unfortunately, but Alex's GOA checks are more comprehensive, so if the data gets through those checks it should be fine for the GO checks.
I think the longer-term plan is to make sure the GO checks are more comprehensive.

**Comment by jseager7** [comment]
Alex has provided a list of warnings from the file (there aren't any actual errors), which I've summarised in the table below, sorted by warning type.

It looks like a few of these warnings are being caused by an extension being edited as text, such as 'occurs_in(apoplast)'.

I guess I can fix the warnings related to with_host_species and with_symbiont_species by just removing those extensions from the GAF file and making sure the relevant taxon IDs are in the taxon ID field. I'll write a script to do that so we can run that over the GAF file before submitting in future.

The has_direct_input extension shouldn't be able to be selected in PHI-Canto anymore, but annotations with that extension might not have had their relation names automatically updated in our curation session database (you probably already fixed this at PomBase).

That just leaves a few warnings that I'm not sure about:

* Incorrect syntax: has_input(binds (UniProt:W5AB81))
* Incorrect syntax: has_input(MGG_08054)
* Invalid range for occurs_in: SO:0001659

@ValWood Do you have any suggestions for those?

Line | PMID | Warning | Source | UniProtKB | Gene
-- | -- | -- | -- | -- | --
182 | PMID:27819043 | Incorrect syntax: has_input(binds (UniProt:W5AB81)) | GO:0140295 part_of(GO:0080185), has_input(binds (UniProt:W5AB81)) | A9JX75 | Tox1
158 | PMID:30610168 | Incorrect syntax: has_input(MGG_08054) | GO:0140311 has_input(MGG_08054), part_of(GO:0062208), occurs_in(GO:0048046) | Q5NBT9 | TPR1
171 | PMID:31804478 | Incorrect syntax: occurs_at(host cell chloroplast) | GO:0004857 has_regulation_target(UniProtKB:Q7X9A6), occurs_at(host cell chloroplast), part_of(GO:0052034) | A0A0L0V3D9 | PSTG_12806
10 | PMID:15096512 | Incorrect syntax: occurs_in(apoplast) | GO:0045087 occurs_in(apoplast), part_of(GO:0002239) | O04678 | P69B
111 | PMID:33203871 | Incorrect syntax: part_of(conidium) | GO:0005737 part_of(conidium) | Q2KEJ2 | HTR1
48 | PMID:31076860 | Incorrect syntax: with_host_species(161934) | GO:0140423 with_host_species(161934) | A0A0K6FU48 | RSOLAG22IIIB_04067
67 | PMID:16965554 | Incorrect syntax: with_host_species(4100) | GO:0080185 with_host_species(4100) | D0NKT5 | PITG_12551
66 | PMID:16965554 | Incorrect syntax: with_host_species(4113) | GO:0080185 with_host_species(4113) | D0NPN8 | Avr3a
82 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0140403 with_host_species(4530), occurs_in(GO:0042025) | Q2KEJ2 | HTR1
83 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0140403 with_host_species(4530), occurs_in(GO:0042025) | G5EHQ6 | HTR2
109 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0042025 with_host_species(4530) | Q2KEJ2 | HTR1
110 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0042025 with_host_species(4530) | G5EHQ6 | HTR2
112 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0085039 with_host_species(4530) | Q2KEJ2 | HTR1
113 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0085039 with_host_species(4530) | G5EHQ6 | HTR2
187 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0001227 occurs_in(GO:0042025), with_host_species(4530), part_of(GO:0140403) | Q2KEJ2 | HTR1
188 | PMID:33203871 | Incorrect syntax: with_host_species(4530) | GO:0001227 occurs_in(GO:0042025), with_host_species(4530), part_of(GO:0140403) | G5EHQ6 | HTR2
79 | PMID:25888589 | Incorrect syntax: with_host_species(4577) | GO:0141017 with_host_species(4577) | A0A0D1C8C8 | See1
167 | PMID:16965554 | Incorrect syntax: with_symbiont_species(4787) | GO:0140376 with_symbiont_species(4787) | Q5I6L8 | Q5I6L8_SOLTU
185 | PMID:33203871 | Invalid range for occurs_in: SO:0001659 | GO:0003677 occurs_in(SO:0001659), occurs_in(GO:0042025), with_host_species(4530), part_of(GO:0140403) | Q2KEJ2 | HTR1
186 | PMID:33203871 | Invalid range for occurs_in: SO:0001659 | GO:0003677 occurs_in(SO:0001659), occurs_in(GO:0042025), with_host_species(4530), part_of(GO:0140403) | G5EHQ6 | HTR2
139 | PMID:30459352 | Unknown/unsupported relation: has_direct_input | GO:0008897 has_direct_input(UniProtKB:F9X6V3) | F9X6V3 | MYCGRDRAFT_91615

**Comment by ValWood** [comment]
ct syntax: has_input(MGG_08054) | GO:0140311 has_input(MGG_08054), part_of(GO:0062208), occurs_in(GO:0048046) | Q5NBT9 | TPR1
-- | -- | -- | --

swap for the Uniprot accession (

**Comment by ValWood** [comment]
Incorrect syntax: occurs_at(host cell chloroplast) | GO:0004857 has_regulation_target(UniProtKB:Q7X9A6), occurs_at(host cell chloroplast), part_of(GO:0052034) | A0A0L0V3D9 | PSTG_12806
-- | -- | -- | --

change to has_input
(not we have more biologist friendly labels to display for these in PomBase, but  most, if not all MF extensions  should be has_input)

**Comment by ValWood** [comment]
orrect syntax: occurs_in(apoplast) | GO:0045087 occurs_in(apoplast), part_of(GO:0002239) | O04678 | P69B

GO only allows occurs_at now, which reads a bit weirdly for apoplast, but....

**Comment by ValWood** [comment]
correct syntax: part_of(conidium) | GO:0005737 part_of(conidium) | Q2KEJ2 | HTR1
-- | -- | -- | --

not sure about that one, it looks OK, try deleting and re-adding
https://wiki.geneontology.org/Annotation_Relations

**Comment by ValWood** [comment]
GO:0003677 occurs_in(SO:0001659),
is DNA binding, occurs_at(promoter)

You can replace this by term+ extension by

[GO:0000979](https://www.ebi.ac.uk/QuickGO/term/GO:0000979)    RNA polymerase II core promoter sequence-specific DNA binding

if it's RNA pol II (otherwise the parent, or a sibling)

**Comment by ValWood** [comment]
Unknown/unsupported relation: has_direct_input | GO:0008897 has_direct_input(UniProtKB:F9X6V3)
-- | --

-> has_input

**Comment by CuzickA** [comment]
Hi, thanks for looking through the GO warnings. Are these changes that I need to make in the sessions within PHI-Canto?

**Comment by ValWood** [comment]
Yep!

**Comment by CuzickA** [comment]
Okay, I'll work through the edits next week.

**Comment by jseager7** [comment]
> not sure about that [conidium] one, it looks OK, try deleting and re-adding

The conidium annotation extension is an error because it's been entered as text. The extension needs to use the term ID BTO:0000283 instead of the 'conidium' text label.

I'm assuming that BTO is a valid ontology for this extension.

**Comment by CuzickA** [comment]
Hi @ValWood,
I've made some of the edits and have some queries above.

Also, do I need to make changes to 'with_the_host_species'?

**Comment by jseager7** [comment]
> Also, do I need to make changes to 'with_the_host_species'?

The with_host_species and with_symbiont_species can stay as they are, I think. My understanding is that we want them for PHI-base curation but they're not valid for the GAF file in that format. I'll need to write a script to move the taxon IDs into the correct column in the GAF file, then I'll remove those extensions from the GAF file export.

**Comment by ValWood** [comment]
correct

**Comment by CuzickA** [comment]
> > Also, do I need to make changes to 'with_the_host_species'?
> 
> The with_host_species and with_symbiont_species can stay as they are, I think. My understanding is that we want them for PHI-base curation but they're not valid for the GAF file in that format. I'll need to write a script to move the taxon IDs into the correct column in the GAF file, then I'll remove those extensions from the GAF file export.

Thanks for the clarification on this.

@ValWood, I have three unhidden comments above that have queries to be resolved. please could you hav a look at these?

**Comment by ValWood** [comment]
I could not sere any other unanswered. @jseager7 has correctly answered the question about species.

Note that I am heading to  the fission yeast  international meeting  inJapan tomorrow so. I  will be out of contact for a week. Responses will be slow

**Comment by CuzickA** [comment]
<html>
<body>


Unknown/unsupported relation: has_direct_input | GO:0008897 has_direct_input(UniProtKB:F9X6V3)
-- | --


<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">-&gt; has_input</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AC edit made 23_05_2023</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Looks like no AE option here for 'has_input', therefore must have been added as text in admin, which I have now updated.</p>
</body>
</html>


DO we need to add an AE option here or are we happy leaving it as admin edit as text?

**Comment by CuzickA** [comment]
I think we still have a query on how to deal with the 'conidium' entry

**Comment by ValWood** [comment]
You would need to use FAO for conidium.

Just so you know has_direct_input was also replaced by has_input, because we  decided that an input for a MF term should always be direct.

**Comment by CuzickA** [comment]
> @ValWood I corrected the 'occurs_at' here. Did you also have a query about 'has_input'? Would this be instead of 'has_regulation_target'?

Yes has_regulation_target has been removed.

Essentially this is captureed by the term itself.
I.e x inhibitor activity has_input y
is the same as
x inbibitor activity has_regulation_target y
This was a simlification becasue there was no difference in meaning

![image](https://github.com/PHI-base/data/assets/11753634/8f7d9bf2-20b6-429d-ad07-38550a7134f5)

So, should I use admin edit as text option to add 'has_input' or one of these available AE options?
![image](https://github.com/PHI-base/data/assets/11753634/94b14ea1-66db-49a2-b342-49d1986503bf)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/data/assets/11753634/1a07d972-3f9c-4e27-b057-f9b0ef3bd746)


I have added the FAO term id for conidium, it doesn't convert to 'conidium' for display
![image](https://github.com/PHI-base/data/assets/11753634/cefc14f1-07b2-4bd6-a02e-f8bd5c87dd2b)
![image](https://github.com/PHI-base/data/assets/11753634/ee5458aa-ec69-4b7c-b281-b780ce6322a3)

**Comment by ValWood** [comment]
> The [PomBase page for GO:0008897](https://www.pombase.org/term/GO:0008897) uses has substrate annotation extensions: not sure if that's what we should be using instead.

has substrate  is our display label for the website. Behind the scenes it's has|_input

We can share our display labels if you want to use them.

For example
protein kinase activity  has_input x will display as 
protein kinase activity phosphorylates y

**Comment by jseager7** [comment]
> I have added the FAO term id for conidium, it doesn't convert to 'conidium' for display

We currently don't load the FAO ontology because I didn't know it was required. @ValWood Do you use this ontology for annotation?

**Comment by ValWood** [comment]
For small fixes like this we do them manually. We have just been updating manually over 1000 alleles as a consequence of  protein sequence coordinate changes. Manu, or new curator wrote some python scripts to fix things where the alleles did not match the protein sequence (the code works out what the allele shoud be). We were able  automate about half of them and the remainder manually. This work will be written up for publication soon, so we will share with you in case it's useful. It will be more difficult for you to track coordinate changes of  proteins  though.

Generally we assess things on a case-by case basis. For the GO logs, so far I have always fixed things manually, because there aren't many changes, it doesn't make sense to automate. But if there were large  bulk changes you would do a bulk edit on the database.

**Comment by ValWood** [comment]
>We currently don't load the FAO ontology because I didn't know it was required. @ValWood Do you use this ontology for annotation?

We only use it for a few extensions, or perhaps it was in FYPO logical defs. I can't remember exactly what, but there are a couple  of things which are outside the scope of GO cellular component so we needed to use it.
@kimrutherford do we have any extensions using FAO (fungal anatomy ontology)?

**Comment by jseager7** [comment]
I've been looking into fixing the with_host_species and with_symbiont_species annotation extensions, and I noticed this guideline for the Taxon column in the [GAF 2.1 documentation](http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/#taxon-column-13):

"For cardinality 2, to be used only in conjunction with terms that have the biological process term multi-organism process or the cellular component term host cell as an ancestor."

All the GO terms to which we've applied the extensions seem to fit this criteria, except for [GO:0140376](https://www.ebi.ac.uk/QuickGO/term/GO:0140376) 'innate immune receptor activity'. See line 167 in the table in the original comment.

We have a rule in our [annotation extension configuration](https://github.com/PHI-base/config/blob/267759519774ed14aaa1f18bbd40586901a54ecd/annotation_extension/phibase_go_extensions.tsv) that enables the with_host_species and with_symbiont_species extensions on [GO:0003674](https://www.ebi.ac.uk/QuickGO/term/GO:0003674) 'molecular_function', but that seems pretty broad, and the GOA checks probably won't allow all the terms in this subset to have  cardinality 2 in the Taxon column.

Probably for now I'll leave the extension on this annotation as it is and hope that it's valid under the GOA rules, unless anyone can see obvious problems with it right now.

**Comment by ValWood** [comment]
I know we used it for something. It must be FYPO. Midori actually maintained it. I'm not sure who maintains it now. Maybe it's me?

**Comment by ValWood** [comment]
Oh my gosh it is too. That was a joke
https://obofoundry.org/ontology/fao.html

**Comment by jseager7** [comment]
I've updated the GAF with the latest changes to the curation sessions (see commit c6d92bf) and I've used a script to fix the 'with species' annotation extensions.

@CuzickA I'm not sure what still needs fixing in the curation sessions so please let me know when you think it's all done.

**Comment by jseager7** [comment]
> Did we resolve the issue of FAO and the conidium term not displaying?

The issue was that 'conidium' was entered as plain text. Since 'conidium' isn't found anywhere in the GAF now (having been replaced by its FAO term), I'm going to assume this is fixed. It remains to be seen whether FAO is accepted by GO as a valid source for terms for this extension. 

> I think there were a couple of examples above where I made the AE edits using the 'edit as text' option as the AE was not available - are we happy to leave these like this or should the AE option be added?

As long as the extension that was entered as text is valid with regards to the GOA rules, we shouldn't have any problems. By 'valid' I mean that the extension has to be named correctly and have a valid range. I think we've already fixed all these cases.

**Comment by jseager7** [comment]
> As the AE has_regulation_target has been removed from GO, it might be worth checking if we have used it in any other PHI-Canto annotations.

I'll need to do a new JSON export to confirm this.

**Comment by jseager7** [comment]
@CuzickA The publications with curation sessions that are still using the has_regulation_target extension are listed below. These are current as of 7 June 2023.

* PMID:17041146
* PMID:28082413
* PMID:30459352
* PMID:30584105
* PMID:31804478

Note that if these sessions are not approved, they will not be included in the GAF export and so don't need to be fixed immediately.

**Comment by CuzickA** [comment]
> The approved sessions are:

PMID:17041146
PMID:30459352
PMID:31804478

@jseager7 I've now made the GO AE edits in these approved sessions.

**Comment by CuzickA** [comment]
I have now also updated the unapproved sessions PMID:28082413 and PMID:30584105.

**Comment by jseager7** [comment]
@CuzickA @ValWood I've got another report on the PHI-base GAF from Alex.

It seems we've somehow used two GO terms that are marked as 'do not annotate':

* GO:0018343 in PMID:31250536,
* GO:0018215 in PMID:30459352.

The FAO term is still not considered valid for the part_of extension, but I don't know if we can fix that besides excluding the extension from the export.

The has_input extension also doesn't seem to accept UniProtKB accession numbers. Not sure if that's a type error or whether we've just provided the accession number in the wrong format.

Line 65:        ERROR   Restricted GO term: gocheck_do_not_annotate     [GO:0018343]
Line 74:        ERROR   Restricted GO term: gocheck_do_not_annotate     [GO:0018215]
Line 100:       WARNING Annotation_extension failed validation  [[GO:0005737] [part_of(FAO:0000024)] [Invalid range for part_of: FAO:0000024]]
Line 141:       WARNING Annotation_extension failed validation  [[GO:0140295] [part_of(GO:0080185),has_input(UniProt:W5AB81)] [Invalid range for has_input: UniProt:W5AB81]]

**Comment by kimrutherford** [comment]
> Line 141: WARNING Annotation_extension failed validation [[GO:0140295]
> [part_of(GO:0080185),has_input(UniProt:W5AB81)] [Invalid range for has_input: UniProt:W5AB81]]

I suspect that the prefix needs to be "UniProtKB:".  PomBase doesn't use UniProt IDs in extensions so I'm not totally sure.

**Comment by jseager7** [comment]
> I suspect that the prefix needs to be "UniProtKB:".

Thanks for spotting that. I think that's the most likely reason. Based on the JSON export, the annotation extension was entered as text, so it's likely not a problem with the GAF export script.

@CuzickA You'll need to change this extension to 'has_input UniProtKB:W5AB81'.

**Comment by jseager7** [comment]
I've updated my previous comment with PMIDs for the other warnings.

**Comment by ValWood** [comment]
I'm not sure about the UniProt prefix part. We make our extensions to PomBAse: and UniProt converts them to uniProt IDs I suspect. The correct format is has_input(DB:accession).
It might be worth checking this with Alex.

**Comment by ValWood** [comment]
Ignore my comment , it should be UniProtKB!

**Comment by jseager7** [comment]
@ValWood I've been looking into the two GO terms in the PHI-base GAF that are marked as do not annotate, protein farnesylation (GO:0018343) and protein phosphopantetheinylation (GO:0018215), and according to QuickGO it seems like they're only marked as do not annotate in the GO SLIM.

For example, see here:

https://www.ebi.ac.uk/QuickGO/term/GO:0018343#termHistory

Timestamp | Action | Category | Detail
-- | -- | -- | --
2023-06-13 | Added | SLIM | gocheck_do_not_annotate

I'm assuming this isn't a valid reason for us to avoid using these terms for annotation? Maybe the GAF validation is using the GO SLIM and that's why these warnings are showing up?

**Comment by ValWood** [comment]
Hi @jseager7  @CuzickA 
I don't know why these appear as SLIM tags, this isn't related to slims, I have reported this to Pascale. (see the ticket linked above).

These "do not annotate" flags are to indicate that these are terms that will be obsoleted from GO at some point in the near future.
This mainly affects terms which were historically added to the biological process ontology, but should only be represented by molecular functions and it is to discourage new annotations to these terms.
This includes terms  like
kinase/phosphorylation
acytyletransferase/acetylation
etc.
We are encouraging curators to identify the actual process that these represent, rather than just recapitulate the molecular function. So for phosphorylation it would often be some "signalling" for acetylation it could be "protein maturation" ot "chromatin remodelling" for example. For farnesylation I have used 

GO:0072659 | protein localization to plasma membrane

but it depends if a process can be inferred from the experiment. Sometimes if it's just an enzyme assay this is not possible.

 This should only operate as a 'soft warning' so I think you can  also ignore these warnings until you are asked to map them over to replacement terms by the GO editors in due course.

**Comment by CuzickA** [comment]
> I suspect that the prefix needs to be "UniProtKB:".

> Thanks for spotting that. I think that's the most likely reason. Based on the JSON export, the annotation extension was entered as text, so it's likely not a problem with the GAF export script.
> 
> @CuzickA You'll need to change this extension to 'has_input UniProtKB:W5AB81'.

Sorry, I missed this one! I've made the change now. Were there any other changes I needed to make?

**Comment by jseager7** [comment]
>  I've made the change now.

Great, thanks.

> Were there any other changes I needed to make?

@CuzickA I don't think so. The only other warning is about the use of an FAO term (conidium) in a GO part_of extension, but I suspect this is a a false positive due to GOA's checks being either too strict or incomplete: it doesn't recognise FAO terms as describing valid anatomical structures, even though FAO should meet the criteria for the extension from the [GO Wiki](https://wiki.geneontology.org/index.php/Annotation_Extension:_Capturing_cell_and_tissue_types#Appropriate_relations_for_adding_cell,_tissue_or_anatomical_structure_contextual_information) shown below.

> part_of Indicates that a GO Cellular Component is part_of a specific cell, tissue, or anatomical structure.

**Comment by jseager7** [comment]
I've exported the latest GAF file where the last remaining warnings are fixed (at least, those that make sense to fix). Thanks to everyone for your help.
