### ISSUE TITLE
header phi-base_current.csv different from phi-base_v4-6_2018-12-05.csv

### ISSUE THREAD

**Issue by jhpoelen** [PHI-base/data#5]
Hi!
I just noticed that the header for your most recent release:

phi-base_current.csv
or 
https://github.com/PHI-base/data/blob/69d20e308be1c385ec2628d48e44c2d360e2d153/releases/phi-base_current.csv

is different from the previous release

phi-base_v4-6_2018-12-05.csv
or 
https://github.com/PHI-base/data/blob/69d20e308be1c385ec2628d48e44c2d360e2d153/releases/phi-base_v4-6_2018-12-05.csv

Is this intentional? 

PS If you enable travis integration, automated checks are performed to detect these kinds of integration related issues. See https://github.com/globalbioticinteractions/template-dataset#enable-integration-testing for more info.

**Comment by jhpoelen** [comment]
Here the diff - 

```shell
$ diff header.txt header_old.txt 
1,2c1,2
< ﻿Curation_comments_temp
< _to_do_
---
> ﻿Curation Comments
> To do
5,32c5,32
< IdentifierTypeOfProteinID
< ProteinID
< IdentifierTypeOfGeneLocusID
< GeneLocusID
< AA sequence #no EMBL#
< NT sequence #no EMBL#
< Genomic sequence providing strain
< Gene_name
< Genome location
< Specific modification/s to the targeted protein or promoter
< Accession ID for the modified genetic element
< Known interacting protein(s) in the pathogen
< Interacting protein - locus ID
< Multiple_mutation
< Pathogen_NCBI_species_Taxonomy ID
< Pathogen_species
< Pathogen_NCBI_strain_Taxonomy_ID
< Experimental_strain
< Disease_name
< Host_descripton
< Host_NCBI_Taxonomy_ID
< Experimental_host_species
< Host_strain_genotype (MOVED this to new col 03/10/2016_or cultivar_taxonomy_ID_NCBI)
< HostGenotype_definedGene of interest
< HostGenotype_definedGene of interest _AccessionID
< tissue_type
< Function
< GO_annotation
---
> Protein ID source
> Protein ID
> Gene ID source
> Gene ID
> AA sequence
> NT sequence
> Sequence Strain
> Gene
> Chr location
> Gene/Protein modification
> Modified gene/protein Id
> Interacting partner(s)
> Interacting partner(s) Id
> Multiple mutation
> Pathogen ID
> Pathogen species
> Pathogen strain ID
> Pathogen strain
> Disease
> Host description
> Host ID
> Host species
> Host strain
> Host genotype
> Host genotype-Id
> Tissue
> Gene Function
> GO annotation
34,57c34,57
< Pathway_secretion_systems
< Phenotype_of_mutant
< Mating_defect_prior_to_penetration
< Pre_penetration_defect
< Penetration_defect
< Post_penetration_defect
< Disease_development_macroscopically_visible _RENAMED_Interaction:Macroscopic pathogen disease development in host
< Vegetative_spores
< Sexual_spores
< In_vitro_growth
< Spore_germination
< Essential_gene_Lethal_knockout
< Inducer
< ChemicalAccession (Chebi/CAS)
< Tested_First_Host_target
< TestedHostTarget_AccessionID
< Interaction phenotype _ RENAMED_ Interaction: Disease outcome
< Host_response _ RENAMED_ Interaction: Macro/microscopic host reponse to pathogen
< experimental_evidence
< Transient Assay Experimental Evidence
< Species_Expert
< Entered_by
< Literature_ID
< Literature_source
---
> Pathway
> Mutant Phenotype
> Mating defect
> Prepenetration defect
> Penetration defect
> Postpenetration defect
> Disease manifestation
> Vegetative spores
> Sexual spores
> Invitro growth
> Spore germination
> Essential gene
> Gene inducer
> Gene inducer Id
> Host target
> Host target Id
> Interaction phenotype
> Host response
> Exp. Technique-stable
> Exp. Technique-transient
> Species expert
> Entered by
> PMID
> Ref. Source
59,60c59,60
< Full_citation
< Author_email
---
> Ref. detail
> Author email
62,63c62,63
< Reference
< Year_published
---
> Author reference
> Year
65,66c65,66
< File_name_pdf_files_provided
< _batch_no_
---
> File name
> Batch no.
68,79c68,87
< _curator_organisation_
< __lab__
< __FG_mycotoxin__
< Additional IdentifierTypeOfGeneLocusID
< Additional GeneLocusID
< Anti-infective (Chemical)
< Compound
< Target site
< Group name
< Chemical group
< Mode in planta
< Mode of action
---
> Curator organization
> Lab
> FG-mycotoxin
> AdditionalIdentifierTypeOfGeneLocusID
> AdditionalGeneLocusID
> Anti infective agent
> Anti infective compound
> Anti infective-target site
> Anti infective group name
> Anti infective Chemical group
> Anti infective-Mode in planta
> Mode of action
> FRAC CODE
> Anti infective-comments
> phi3pars
> Horizontal gene transfer
> phi3_pars
>  Pathogen gene maps
> Host gene maps
> 
```

**Comment by jhpoelen** [comment]
If changes are intended, please update your schema definition accordingly  https://github.com/PHI-base/data/blob/master/phi-base-schema.json . Happy to help if needed!

**Comment by CuzickA** [comment]
Thank you for your message @jhpoelen 

@martin2urban Can you please look into this as we briefly discussed?

**Comment by jhpoelen** [comment]
I'd be great if we could fix this sooner rather than later because GloBI is unable to index your data now.

**Comment by jhpoelen** [comment]
@CuzickA @martin2urban Please let me know I can help.

**Comment by martin2urban** [comment]
@jhpoelen :  I just uploaded a revised file, that should comply with https://github.com/PHI-base/data/blob/master/phi-base-schema.json. The first two lines are the same as in phi-base_v4-6_2018-12-05.csv.  Let me know in case of remaining issues.

**Comment by jhpoelen** [comment]
Looking much better! The remaining issues are:

1. missing trailing columns (e.g., FRAC CODE, Anti infective-comments, phi3pars, Horizontal gene transfer, phi3_pars, Pathogen gene maps, Host gene maps, for example, see below). If you no longer expect to expose / support these columns, suggest to remove them from the header schema at ```phi-base-schema.json```. 

```shell
$ diff <(head -n1 phi-base_current.csv | tr ',' '\n') <(head -n1 phi-base_v4-6_2018-12-05.csv | tr ',' '\n')
79c79,87
< Mode of action
---
> Mode of action
> FRAC CODE
> Anti infective-comments
> phi3pars
> Horizontal gene transfer
> phi3_pars
>  Pathogen gene maps
> Host gene maps
> 
```


2. duplicate header - looks like the file phi-base_current.csv has two header lines:

```shell
$ head -n3 releases/phi-base_current.csv 
Curation Comments,To do,Record ID,PHI_MolConn_ID,Protein ID source,Protein ID,Gene ID source,Gene ID,AA sequence,NT sequence,Sequence Strain,Gene,Chr location,Gene/Protein modification,Modified gene/protein Id,Interacting partner(s),Interacting partner(s) Id,Multiple mutation,Pathogen ID,Pathogen species,Pathogen strain ID,Pathogen strain,Disease,Host description,Host ID,Host species,Host strain,Host genotype,Host genotype-Id,Tissue,Gene Function,GO annotation,Database,Pathway,Mutant Phenotype,Mating defect,Prepenetration defect,Penetration defect,Postpenetration defect,Disease manifestation,Vegetative spores,Sexual spores,Invitro growth,Spore germination,Essential gene,Gene inducer,Gene inducer Id,Host target,Host target Id,Interaction phenotype,Host response,Exp. Technique-stable,Exp. Technique-transient,Species expert,Entered by,PMID,Ref. Source,DOI,Ref. detail,Author email,Comments,Author reference,Year,Curation details,File name,Batch no.,Curation date,Curator organization,Lab,FG-mycotoxin,AdditionalIdentifierTypeOfGeneLocusID,AdditionalGeneLocusID,Anti infective agent,Anti infective compound,Anti infective-target site,Anti infective group name,Anti infective Chemical group,Anti infective-Mode in planta,Mode of action
Curation Comments,To do,Record ID,PHI_MolConn_ID,Protein ID source,Protein ID,Gene ID source,Gene ID,AA sequence,NT sequence,Sequence Strain,Gene,Chr location,Gene/Protein modification,Modified gene/protein Id,Interacting partner(s),Interacting partner(s) Id,Multiple mutation,Pathogen ID,Pathogen species,Pathogen strain ID,Pathogen strain,Disease,Host description,Host ID,Host species,Host strain,Host genotype,Host genotype-Id,Tissue,Gene Function,GO annotation,Database,Pathway,Mutant Phenotype,Mating defect,Prepenetration defect,Penetration defect,Postpenetration defect,Disease manifestation,Vegetative spores,Sexual spores,Invitro growth,Spore germination,Essential gene,Gene inducer,Gene inducer Id,Host target,Host target Id,Interaction phenotype,Host response,Exp. Technique-stable,Exp. Technique-transient,Species expert,Entered by,PMID,Ref. Source,DOI,Ref. detail,Author email,Comments,Author reference,Year,Curation details,File name,Batch no.,Curation date,Curator organization,Lab,FG-mycotoxin,AdditionalIdentifierTypeOfGeneLocusID,AdditionalGeneLocusID,Anti infective agent,Anti infective compound,Anti infective-target site,Anti infective group name,Anti infective Chemical group,Anti infective-Mode in planta,Mode of action
,,Record 1,PHI:3,Uniprot,P26215,EMBL,AAA79885,,,SB111,PGN1,,,,,,,5017,Bipolaris zeicola,,SB111,Leaf spot,Monocots,4577,Zea mays (related: maize),,,,,Endopolygalacturonase,GO:0004650,GO,,unaffected pathogenicity,,no,no,no,,,,,,,pectin,,,,,,Gene disruption,,,MU; JA,2152162,PubMed,10.1105/tpc.2.12.1191,,,Expression during all infection stages. pathogen formerly called Cochliobolus carbonum teleomorph name,Scott-Craig et al.,1990,,,PHI-base Vers.3.3,04/05/2005,Rres,,,,,,,,,,,
```

Please let me know how I can help.

**Comment by jhpoelen** [comment]
@martin2urban @CuzickA just so that you know: your phi-based data is still not getting indexed properly by GloBI due to schema mismatch (see https://github.com/PHI-base/data/issues/5#issuecomment-505134404). I am wondering whether the missing columns ```FRAC CODE, Anti infective-comments, phi3pars, Horizontal gene transfer, phi3_pars, Pathogen gene maps, Host gene maps``` are missing by accident or on purpose.  Please advise.

**Comment by martin2urban** [comment]
@jhpoelen : I updated the file, so hopefully it is working now.  Thanks for your offer of help. Would it be possible to arrange a SKYPE call when convenient? I am eager to learn more about Travis and how the phi-base-schema.json file could be changed without affecting your build.

**Comment by jhpoelen** [comment]
Happy to elaborate on GloBI usage of travis to keep track of the health of data integrations. Please suggest date / time . Please note that I am in pacific time zone.

**Comment by martin2urban** [comment]
@jhpoelen : Thanks for the recent Skype that clarified a few things for me.
I tried adjusting the new sheet to the old format, but this didn't work. I believe a few 'empty' fields in the  phi-base-schema.json file are the problem.  I could not identify a difference between the old and new version headers when counting ',' separators  and applying your  earlier 'diff' command using linux commands.

![image](https://user-images.githubusercontent.com/2812591/61594170-58105480-abe0-11e9-8962-c4449e79c77c.png)

**Comment by martin2urban** [comment]
@jhpoelen: We are thinking of changing our database format in the future considerably. I am wondering if we could provide in the meantime a SLIM format  for our database. We also provide Ensembl Genomes and FungiDB with  a SLIM format using email. Perhaps the TRAVIS file could be changed to link to phi-slim-current.csv to contain only the 'essential columns' in use by GLOBI?

**Comment by jhpoelen** [comment]
@martin2urban (apologies for the delay - just came back from a hiking trip) 

re: mismatching column / value count - On closer inspection, I found that the number of columns in data lines is 79 whereas the header has the expected 86 values.

For instance:
```shell
$ cat releases/phi-base_current.csv | head -n1 | tr ',' '\n' | wc -l
87 <--- number of column names in first line
$ cat releases/phi-base_current.csv | tail -n+2 | head -n1 | tr ',' '\n' | wc -l
79   <--- number of values in second line
```
While I'd hope that csv files have same number of fields on each line, I'll make the GloBI / elton a little more lenient. Rather than giving up, GloBI will simply set all missing tailing values to null and log a warning about it. I would recommend to make sure that csv files have consistent number of columns across header and value lines. 

As far as the SLIM format goes - I am striving towards adopting data formats that work best for those publishing the data, so simply add a new issue whenever the files are available. For now, I am hoping to keep the existing solution in place.

**Comment by jhpoelen** [comment]
@martin2urban fyi - I just released globi/elton versions with a more lenient parser. Changes should propagate in the next couple of days.

**Comment by jhpoelen** [comment]
The more lenient parser is able to deal with the reported mismatch between header / rows columns. Am still suggesting to fix it if you have the time, but closing this issue because GloBI is able to get to the data again.
